version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - skip-changelog
      - dependencies
    ignore:
      - dependency-name: 'eslint*'
      - dependency-name: 'prettier*'
